#!/bin/sh

SOB=$(git var GIT_AUTHOR_IDENT | sed -n "s/^\(.*>\).*$/Signed-off-by: \1/p")
grep -qs "^$SOB""$1"|| echo "$SOB" >> "$1".tmp;

(echo; sed -e '/^$/d' "$1") >> "$1".tmp
mv "$1".tmp "$1";

# From https://habr.com/ru/post/75063/
